CREATE DATABASE ridu1la35qvgr5kf;

USE ridu1la35qvgr5kf;

CREATE TABLE groceries (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  cost FLOAT UNSIGNED NOT NULL,
  purchased BOOL NOT NULL
);